### ISSUE TITLE
Intermittent Bad Requests for URL from Ravello

### ISSUE THREAD

**Issue by dbenoit17** [sborenst/ansible_agnostic_deployer#60]
The following error occurs occasionally:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 684, in <module>
    main()
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 310, in main
    create_app_and_publish(client, module)
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 652, in create_app_and_publish
    app = client.create_application(app)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 539, in create_application
    return self.request('POST', '/applications', app)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 359, in request
    response = self._request(method, path, body, headers)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 430, in _request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.ravellosystems.com/api/v1/applications

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ravello_app"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 684, in <module>\n    main()\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 310, in main\n    create_app_and_publish(client, module)\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 652, in create_app_and_publish\n    app = client.create_application(app)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 539, in create_application\n    return self.request('POST', '/applications', app)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 359, in request\n    response = self._request(method, path, body, headers)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 430, in _request\n    response.raise_for_status()\n  File \"/usr/lib/python2.7/site-packages/requests/models.py\", line 893, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.ravellosystems.com/api/v1/applications\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```
Usually, running the deployment again will overcome it.  

TODO:
- Verify requests are being sent correctly during these cases
- See if implementing play retries fixes the issue

**Comment by dbenoit17** [comment]
Seems to occur in the same context as:
https://github.com/sborenst/ansible_agnostic_deployer/issues/59

**Comment by dbenoit17** [comment]
This has been merged with another issue here:
#67
