### ISSUE TITLE
collision errors during simultaneous deployments

### ISSUE THREAD

**Issue by dbenoit17** [sborenst/ansible_agnostic_deployer#67]
Affects Ravello Deployments.

Control Path Collisions, as discussed here:
```
fatal: [node.rhpds.opentlc.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips [date_redacted]
debug1: Reading configuration data /root/ansible_agnostic_deployer/ansible/workdir/ocp-demo-lab_david-an28_ssh_conf
debug1: auto-mux: Trying existing master
debug1: Control socket \"/tmp/node.rhpds.opentlc.com-cloud-user\" does not exist
debug1: Executing proxy command: exec ssh -i /root/ansible_agnostic_deployer/ansible/workdir/david-an28key -W node.rhpds.opentlc.com:22 -q cloud-user@bastionhost-ocpdemolab[id_redacted].srv.ravcloud.com
debug3: timeout: 60000 ms remain after connect
debug1: permanently_set_uid: 0/0 
debug3: Incorrect RSA1 identifier
debug3: Could not load \"/root/ansible_agnostic_deployer/ansible/workdir/david-an28key\" as a RSA1 public key
debug1: identity file /root/ansible_agnostic_deployer/ansible/workdir/david-an28key type 1
debug1: identity file /root/ansible_agnostic_deployer/ansible/workdir/david-an28key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: permanently_drop_suid: 0
Connection timed out during banner exchange
",
    "unreachable": true
}
```

Bad URL Requests
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 684, in <module>
    main()
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 310, in main
    create_app_and_publish(client, module)
  File "/tmp/ansible_OuAa2l/ansible_module_ravello_app.py", line 652, in create_app_and_publish
    app = client.create_application(app)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 539, in create_application
    return self.request('POST', '/applications', app)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 359, in request
    response = self._request(method, path, body, headers)
  File "/usr/lib/python2.7/site-packages/ravello_sdk.py", line 430, in _request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.ravellosystems.com/api/v1/applications

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ravello_app"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 684, in <module>\n    main()\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 310, in main\n    create_app_and_publish(client, module)\n  File \"/tmp/ansible_OuAa2l/ansible_module_ravello_app.py\", line 652, in create_app_and_publish\n    app = client.create_application(app)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 539, in create_application\n    return self.request('POST', '/applications', app)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 359, in request\n    response = self._request(method, path, body, headers)\n  File \"/usr/lib/python2.7/site-packages/ravello_sdk.py\", line 430, in _request\n    response.raise_for_status()\n  File \"/usr/lib/python2.7/site-packages/requests/models.py\", line 893, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.ravellosystems.com/api/v1/applications\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

**Comment by dbenoit17** [comment]
Add `ansible_ssh_common_args: '-o ConnectionAttempts=<desired retries>'` to ssh_vars.yml
